- id: owasp-agentic-scan
  name: OWASP Agentic AI Scanner
  description: Scan for OWASP Agentic AI Top 10 security risks
  entry: owasp-scan scan
  language: python
  types: [python]
  require_serial: true
  minimum_pre_commit_version: "2.9.0"
